#Xavier Rouleau
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Brouillon2\DialogRecherche.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog_Recherche):
        Dialog_Recherche.setObjectName("Dialog_Recherche")
        Dialog_Recherche.resize(654, 599)
        self.label_enclos_animal = QtWidgets.QLabel(Dialog_Recherche)
        self.label_enclos_animal.setGeometry(QtCore.QRect(40, 70, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_enclos_animal.setFont(font)
        self.label_enclos_animal.setObjectName("label_enclos_animal")
        self.comboBox_enclos_animal = QtWidgets.QComboBox(Dialog_Recherche)
        self.comboBox_enclos_animal.setGeometry(QtCore.QRect(40, 100, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_enclos_animal.setFont(font)
        self.comboBox_enclos_animal.setObjectName("comboBox_enclos_animal")
        self.comboBox_enclos_animal.addItem("")
        self.comboBox_enclos_animal.setItemText(0, "")
        self.comboBox_enclos_animal.addItem("")
        self.comboBox_enclos_animal.setItemText(1, "")
        self.comboBox_enclos_animal.addItem("")
        self.comboBox_enclos_animal.setItemText(2, "")
        self.listView_list_animaux = QtWidgets.QListView(Dialog_Recherche)
        self.listView_list_animaux.setGeometry(QtCore.QRect(40, 220, 501, 341))
        self.listView_list_animaux.setObjectName("listView_list_animaux")
        self.label_listView_list_animaux_enclos = QtWidgets.QLabel(Dialog_Recherche)
        self.label_listView_list_animaux_enclos.setGeometry(QtCore.QRect(50, 190, 531, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_listView_list_animaux_enclos.setFont(font)
        self.label_listView_list_animaux_enclos.setObjectName("label_listView_list_animaux_enclos")
        self.pushButton_afficher = QtWidgets.QPushButton(Dialog_Recherche)
        self.pushButton_afficher.setGeometry(QtCore.QRect(380, 100, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_afficher.setFont(font)
        self.pushButton_afficher.setObjectName("pushButton_afficher")

        self.retranslateUi(Dialog_Recherche)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Recherche)

    def retranslateUi(self, Dialog_Recherche):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Recherche.setWindowTitle(_translate("Dialog_Recherche", "Dialog recherche"))
        self.label_enclos_animal.setText(_translate("Dialog_Recherche", "Enclos de l\'animal"))
        self.label_listView_list_animaux_enclos.setText(_translate("Dialog_Recherche", "Listview  affichant la liste des animaux qui vivent dans  l\'enclos :"))
        self.pushButton_afficher.setText(_translate("Dialog_Recherche", "Afficher"))
